### ISSUE TITLE
Referenzseiten Sortierbar machen

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-navigation#18]
Akteull ist es so, dass bei einer Auswahl von mehreren Referenzseiten die Reihenfolge der Referenzseiten durch die Reihenfolge in der Seitenstruktur bestimmt wird. Es wäre sehr praktisch, wenn die (wie bei einer Galerie) auch individuell sortierbar wären an der Stelle.

Viele Grüße

**Comment by backbone87** [comment]
ich glaube die Navigation nutzt noch kein selectri, sondern die Container interne seitenauswahl? Bei letztere war ein sortieren der Auswahl nicht möglich (zumindest war das mein letzter Stand)

**Comment by frontendschlampe** [comment]
ich werde das nächste Woche mal mit @dmolineus prüfen ...

**Comment by frontendschlampe** [comment]
@MacKP wie besprochen, ist es möglich,

wenn du dann Bedarf hast, gib einfach Bescheid

**Comment by dmolineus** [comment]
Implementiert mit 4b21ef0 und released als Version 1.9.0
