### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by Webstylerin** [hofff/contao-navigation#19]
Aktuelll benötigt die Erweiterung noch php: ^5.3 || ^7.0, ist eine Anpassung auf PHP 8 geplant?

Ich setze die Erweiterung sehr oft ein, allerdings wird PHP 7.4 nur noch bis Ende 2022 mit Sicherheitsupdates unterstützt. Ich bräuchte also etwas Planbarkeit. :)

**Comment by frontendschlampe** [comment]
Hey @Webstylerin

Natürlich planen wir eine entsprechende Anpassung. Ich gehe davon aus, dass diese innerhalb der nächsten 6-8 Wochen zur Verfügung stehen wird.

**Comment by Webstylerin** [comment]
Super! Damit kann ich arbeiten. Vielen Dank.

**Comment by frontendschlampe** [comment]
Hallo, wir haben bereits eine dev-Version mit PHP 8 und Contao 4.13 Kompatibilität am Start. Probiert gern einmal den develop-Branch … `"hofff/contao-navigation": "dev-develop"`

Wir werden demnächst eine stable-Version veröffentlichen.

**Comment by ericgerhardy** [comment]
Wow, vielen Dank für die schnelle Antwort! Den dev-Branch habe ich schon gesehen, dann werde ich das mal lokal testen und für die Live-Seite ggfs. auf die stable-Version warten. Danke für eure Arbeit!

**Comment by Webstylerin** [comment]
Die "dev-develop"-Version habe ich mittlerweile schon ein paar mal mit PHP 8 im Einsatz und konnte bisher keine Probleme festestellen.

Ich freue mich auf den stable-Release. Vielen Dank!

**Comment by Tastaturberuf** [comment]
*hust*

**Comment by dmolineus** [comment]
Version 2.0.0 ist veröffentlicht.
