### ISSUE TITLE
Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by martinfrese** [hofff/contao-navigation#20]
Hello, I'm using the develop branch and php8.0 in my project.

If I enter the module in backend with debug modus on, I get the title warning message.

Stack Trace:
ErrorException:
Warning: Trying to access array offset on value of type null

  at vendor/hofff/contao-navigation/src/EventListener/Dca/NavigationDcaListener.php:46
  at Hofff\Contao\Navigation\EventListener\Dca\NavigationDcaListener->getPageFields()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:1319)
  at Contao\Widget::getAttributesFromDca()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:433)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1942)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:44)
     

vendor/hofff/contao-navigation/src/EventListener/Dca/NavigationDcaListener.php:46
Code Snippet:
      `41    foreach ($GLOBALS['TL_DCA']['tl_page']['fields'] as $fieldName => &$config) {      `        
      `42    if (isset(PageQueryBuilder::DEFAULT_FIELDS[$fieldName])) {                 ` 
      `43    continue;             ` 
      `44    }             ` 
      `45       ` 
      `46    $fields[$fieldName] = sprintf('%s <span class="tl_gray">[%s]</span>', $config['label'][0], $fieldName);        ` 
      `47    }`

**Comment by Webstylerin** [comment]
I use this extension in several Contao 4.13 + PHP 8 installations. Today I upgraded a website with Contao 4.9 to 4.13 (IONOS, PHP 8.2) and discovered this error for the first time. I tried uninstalling and deleting, but the error occurs immediately when I try to open the module in the backend.

Does anyone have a solution? Is the extension still being actively worked on?

Kind regards, Nicole

**Comment by frontendschlampe** [comment]
Yes … the extension is still active. Please install `dev-develop` branch for PHP 8. We're using the branch in various projects. We'll release a new stable version soon …

**Comment by dmolineus** [comment]
Version 2.0.0 ist veröffentlicht.
